---
- name: Install Nginx on backends
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create custom index.html using magic variable
  ansible.builtin.copy:
    content: "Hello from {{ inventory_hostname }}!\n"
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Ensure Nginx is running and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
